<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>QoindDigital</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ff4bccf3-d61d-4ea2-9ad1-d2604842c1ae</testSuiteGuid>
   <testCaseLink>
      <guid>3043da30-9ce8-416f-9b16-299ca4a117a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Get List of User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bce18f65-e230-462f-874c-bdaa203cc2ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ffb76b5-1fba-451c-a8d3-6fd2e296f7ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b52cce7f-2747-42cf-9562-ac1de09b311a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Get Single User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f417177b-0c4a-4790-ab4b-7be42581e0ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8758550d-cfb1-4581-8da3-06cf89b8f5bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3bfe0c17-92be-4263-8c77-3a79440016e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Update User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fa2cb9d-603f-493d-a53a-6651c2dd21d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>636b60e1-457d-4f67-b367-37e8dd59606c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae2e3a19-3c36-4b9e-97c0-0c291ff15423</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>'1'</defaultValue>
         <description></description>
         <id>f79eec82-f765-43b3-a259-f583a888c210</id>
         <masked>false</masked>
         <name>userId</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Register User</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3d7a3359-6c26-43ea-bd09-f95c1b66b7f7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/RegisterUser</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3d7a3359-6c26-43ea-bd09-f95c1b66b7f7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userId</value>
         <variableId>f79eec82-f765-43b3-a259-f583a888c210</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3d7a3359-6c26-43ea-bd09-f95c1b66b7f7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>343add88-3022-4ef6-a815-199e6cb57083</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3d7a3359-6c26-43ea-bd09-f95c1b66b7f7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>37d9750c-cb56-4151-a4ed-92a2ee3c33fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>886c64a2-86e1-40ad-9bee-8d7215a4e0b1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
